# Use official Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy app code to the container
COPY . .

# Install Python dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# Expose the port your Flask app runs on
EXPOSE 8080

# Run the Flask app using Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:8080", "app:app"]
