apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-cicd
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sovitbhandari/Advanced-CICD-Project.git
    path: kubernetes
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
